### ISSUE TITLE
[ERROR] panic: no NBD module loaded

### ISSUE THREAD

**Issue by darkterminal** [pojntfx/ram-dl#1]
OS: Linux Mint 21.1 x86_64
Host: 4291ED9 ThinkPad X220
Kernel: 5.15.0-76-generic

```sheel
➜ sudo ram-dl --raddr localhost:1337
2023/07/01 11:12:04 Connected to localhost:1337
panic: no NBD module loaded

goroutine 1 [running]:
main.main()
	/data/cmd/ram-dl/main.go:51 +0xf47
```

**Comment by pojntfx** [comment]
This is based on `nbd`, so be sure to run `sudo modprobe nbd` first :)

**Comment by darkterminal** [comment]
:tada: It's working! Thank you very much!

I think this issue needs to be written on `README.md`

**Comment by pojntfx** [comment]
You're right; I've added it here: https://github.com/pojntfx/ram-dl#2-download-ram

Thanks again!

**Comment by darkterminal** [comment]
Yeah... also thank you I have been faking my RAM and got real performance!!! Well done!!! 🎉
